#include <ncurses.h>

#include <algorithm>
#include <cerrno>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <string>
#include <system_error>
#include <unistd.h>
#include <vector>

namespace {

struct Setting {
    std::string key;
    std::string label;
    std::string help;
    std::vector<std::string> choices;
    std::string value;
    bool isBoolean;
};

const std::vector<Setting> settingDefinitions = {
    {"CONFIG_SAMPLE_RATE", "Audio sample rate (Hz)",
     "Build-time engine sample rate. The USB sample rate in /audiox/config.txt remains independently configurable.",
     {"8000", "16000", "22050", "32000", "44100", "48000", "96000"}, "", false},
    {"CONFIG_BUFFER_FRAMES", "Audio buffer frames",
     "Sets the number of frames processed per audio block. Larger values increase latency and reduce scheduling pressure.",
     {"64", "128", "256", "512", "1024"}, "", false},
    {"CONFIG_ALSA_LOGS", "Enable ALSA diagnostics",
     "Enables additional ALSA diagnostics in the runtime log.", {"n", "y"}, "", true},
    {"CONFIG_DEBUG_SHELL", "Enable boot debug shell",
     "Enables the temporary debug shell during boot. Keep disabled for normal use.", {"n", "y"}, "", true},
};

constexpr int minimumRows = 22;
constexpr int minimumColumns = 68;
constexpr int leftPaneWidth = 39;

std::string trim(const std::string& value) {
    const std::string whitespace = " \t\r\n";
    const auto first = value.find_first_not_of(whitespace);
    if (first == std::string::npos) {
        return {};
    }
    const auto last = value.find_last_not_of(whitespace);
    return value.substr(first, last - first + 1);
}

std::vector<Setting> loadKconfigDefaults(const std::string& kconfigPath) {
    std::vector<Setting> settings = settingDefinitions;
    std::ifstream kconfig(kconfigPath);
    std::string activeSymbol;
    std::string line;
    while (std::getline(kconfig, line)) {
        line = trim(line);
        if (line.rfind("config ", 0) == 0) {
            activeSymbol = "CONFIG_" + trim(line.substr(7));
            continue;
        }
        if (line.rfind("default ", 0) != 0) {
            continue;
        }
        const std::string value = trim(line.substr(8));
        for (auto& setting : settings) {
            if (setting.key == activeSymbol &&
                std::find(setting.choices.begin(), setting.choices.end(), value) != setting.choices.end()) {
                setting.value = value;
            }
        }
    }

    for (auto& setting : settings) {
        if (setting.value.empty()) {
            setting.value = setting.choices.front();
        }
    }
    return settings;
}

std::vector<Setting> loadSettings(const std::string& configPath, const std::string& kconfigPath) {
    std::vector<Setting> settings = loadKconfigDefaults(kconfigPath);
    std::ifstream input(configPath);
    std::string line;
    while (std::getline(input, line)) {
        line = trim(line);
        if (line.rfind("# ", 0) == 0) {
            const auto marker = line.find(" is not set");
            if (marker != std::string::npos) {
                const std::string key = line.substr(2, marker - 2);
                for (auto& setting : settings) {
                    if (setting.key == key && setting.isBoolean) {
                        setting.value = "n";
                    }
                }
            }
            continue;
        }

        const auto separator = line.find('=');
        if (separator == std::string::npos) {
            continue;
        }
        const std::string key = line.substr(0, separator);
        const std::string value = line.substr(separator + 1);
        for (auto& setting : settings) {
            if (setting.key == key &&
                std::find(setting.choices.begin(), setting.choices.end(), value) != setting.choices.end()) {
                setting.value = value;
            }
        }
    }
    return settings;
}

bool saveSettings(const std::string& configPath, const std::vector<Setting>& settings, std::string& error) {
    const std::filesystem::path destination(configPath);
    std::error_code filesystemError;
    if (!destination.parent_path().empty()) {
        std::filesystem::create_directories(destination.parent_path(), filesystemError);
        if (filesystemError) {
            error = filesystemError.message();
            return false;
        }
    }

    const std::string temporaryPath = configPath + ".tmp";
    {
        std::ofstream output(temporaryPath, std::ios::trunc);
        if (!output) {
            error = "cannot write " + temporaryPath;
            return false;
        }
        output << "#\n# audiox configuration\n# Generated by make menuconfig; use make defconfig to reset.\n#\n";
        for (const auto& setting : settings) {
            if (setting.isBoolean && setting.value == "n") {
                output << "# " << setting.key << " is not set\n";
            } else {
                output << setting.key << '=' << setting.value << '\n';
            }
        }
        output.flush();
        if (!output) {
            error = "failed writing " + temporaryPath;
            return false;
        }
    }

    if (std::rename(temporaryPath.c_str(), configPath.c_str()) != 0) {
        error = "cannot replace " + configPath + ": " + std::strerror(errno);
        std::remove(temporaryPath.c_str());
        return false;
    }
    return true;
}

std::string displayValue(const Setting& setting) {
    if (setting.isBoolean) {
        return setting.value == "y" ? "[*]" : "[ ]";
    }
    return "< " + setting.value + " >";
}

void drawWrapped(int y, int x, int width, const std::string& text) {
    int currentY = y;
    std::string line;
    std::string word;
    std::size_t index = 0;
    while (index <= text.size()) {
        if (index == text.size() || text[index] == ' ') {
            if (!word.empty()) {
                const std::string candidate = line.empty() ? word : line + " " + word;
                if (static_cast<int>(candidate.size()) > width && !line.empty()) {
                    mvaddnstr(currentY++, x, line.c_str(), width);
                    line = word;
                } else {
                    line = candidate;
                }
                word.clear();
            }
            ++index;
            continue;
        }
        word.push_back(text[index++]);
    }
    if (!line.empty()) {
        mvaddnstr(currentY, x, line.c_str(), width);
    }
}

void drawScreen(const std::vector<Setting>& settings, std::size_t selected, const std::string& status) {
    erase();
    int rows = 0;
    int columns = 0;
    getmaxyx(stdscr, rows, columns);

    attron(COLOR_PAIR(1) | A_BOLD);
    mvhline(0, 0, ' ', columns);
    mvaddnstr(0, 2, "audiox Configuration", columns - 4);
    attroff(COLOR_PAIR(1) | A_BOLD);
    mvaddnstr(1, 2, "Configure the runtime build", columns - 4);
    mvhline(2, 0, ACS_HLINE, columns);

    if (rows < minimumRows || columns < minimumColumns) {
        mvaddstr(4, 2, "Terminal is too small for menuconfig.");
        mvaddstr(6, 2, "Resize to at least 68 columns by 18 rows, then retry.");
        mvaddstr(rows - 2, 2, "Press q to exit");
        refresh();
        return;
    }

    const int rightPaneX = leftPaneWidth + 2;
    const int footerRow = rows - 1;
    mvaddstr(3, 2, "Audio engine");
    mvaddstr(8, 2, "Development");
    const int settingRows[] = {4, 5, 6, 9};

    for (std::size_t index = 0; index < settings.size(); ++index) {
        const int row = settingRows[index];
        const std::string value = displayValue(settings[index]);
        const int labelWidth = leftPaneWidth - static_cast<int>(value.size()) - 6;
        if (index == selected) {
            attron(A_REVERSE | A_BOLD);
        }
        mvaddch(row, 2, index == selected ? '>' : ' ');
        mvaddnstr(row, 4, settings[index].label.c_str(), labelWidth);
        mvaddstr(row, leftPaneWidth - static_cast<int>(value.size()) - 1, value.c_str());
        if (index == selected) {
            attroff(A_REVERSE | A_BOLD);
        }
    }

    mvvline(3, leftPaneWidth, ACS_VLINE, footerRow - 3);
    mvaddnstr(3, rightPaneX, settings[selected].label.c_str(), columns - rightPaneX - 2);
    mvhline(4, rightPaneX, ACS_HLINE, columns - rightPaneX - 2);
    drawWrapped(6, rightPaneX, columns - rightPaneX - 4, settings[selected].help);

    int choiceRow = 11;
    mvaddstr(choiceRow++, rightPaneX, "Available values:");
    for (const auto& choice : settings[selected].choices) {
        const bool active = choice == settings[selected].value;
        if (active) {
            attron(A_BOLD | COLOR_PAIR(2));
        }
        mvaddstr(choiceRow++, rightPaneX + 2, active ? "> " : "  ");
        mvaddstr(choiceRow - 1, rightPaneX + 4, choice.c_str());
        if (active) {
            attroff(A_BOLD | COLOR_PAIR(2));
        }
    }

    mvhline(rows - 3, 0, ACS_HLINE, columns);
    if (!status.empty()) {
        mvaddnstr(rows - 2, 2, status.c_str(), columns - 4);
    }
    attron(A_REVERSE);
    mvhline(footerRow, 0, ' ', columns);
    mvaddnstr(footerRow, 1, " Up/Down Select   Left/Right Change   Enter Choose   S Save   R Defaults   Q Exit   ? Help ", columns - 2);
    attroff(A_REVERSE);
    refresh();
}

int chooseValue(const Setting& setting) {
    const int height = static_cast<int>(setting.choices.size()) + 4;
    const int width = 36;
    int rows = 0;
    int columns = 0;
    getmaxyx(stdscr, rows, columns);
    WINDOW* dialog = newwin(height, width, (rows - height) / 2, (columns - width) / 2);
    if (!dialog) {
        return -1;
    }
    keypad(dialog, TRUE);
    box(dialog, 0, 0);
    mvwaddnstr(dialog, 1, 2, setting.label.c_str(), width - 4);

    const auto current = std::find(setting.choices.begin(), setting.choices.end(), setting.value);
    int choice = current == setting.choices.end() ? 0 : static_cast<int>(current - setting.choices.begin());
    while (true) {
        for (std::size_t index = 0; index < setting.choices.size(); ++index) {
            if (static_cast<int>(index) == choice) {
                wattron(dialog, A_REVERSE | A_BOLD);
            }
            mvwaddnstr(dialog, static_cast<int>(index) + 2, 2, setting.choices[index].c_str(), width - 4);
            if (static_cast<int>(index) == choice) {
                wattroff(dialog, A_REVERSE | A_BOLD);
            }
        }
        wrefresh(dialog);
        const int key = wgetch(dialog);
        if (key == KEY_UP || key == 'k') {
            choice = (choice + static_cast<int>(setting.choices.size()) - 1) % static_cast<int>(setting.choices.size());
        } else if (key == KEY_DOWN || key == 'j') {
            choice = (choice + 1) % static_cast<int>(setting.choices.size());
        } else if (key == KEY_ENTER || key == '\n' || key == '\r') {
            delwin(dialog);
            return choice;
        } else if (key == 27 || key == 'q') {
            delwin(dialog);
            return -1;
        }
    }
}

bool showHelp() {
    int rows = 0;
    int columns = 0;
    getmaxyx(stdscr, rows, columns);
    const int width = std::min(columns - 4, 64);
    const int height = 10;
    WINDOW* dialog = newwin(height, width, (rows - height) / 2, (columns - width) / 2);
    if (!dialog) {
        return false;
    }
    box(dialog, 0, 0);
    mvwaddstr(dialog, 1, 2, "Menu controls");
    mvwaddstr(dialog, 3, 2, "Arrow keys move through settings and change values.");
    mvwaddstr(dialog, 4, 2, "Enter opens the value selector or toggles a boolean.");
    mvwaddstr(dialog, 5, 2, "S saves .config. R restores Kconfig defaults.");
    mvwaddstr(dialog, 6, 2, "Q exits; unsaved changes prompt before leaving.");
    mvwaddstr(dialog, height - 2, 2, "Press any key to return");
    wrefresh(dialog);
    wgetch(dialog);
    delwin(dialog);
    return true;
}

int confirmExit() {
    const std::string prompt = "Save changes before exiting?  y: save  n: discard  c: continue";
    const int row = LINES - 4;
    attron(A_REVERSE | A_BOLD);
    mvhline(row, 0, ' ', COLS);
    mvaddnstr(row, 2, prompt.c_str(), COLS - 4);
    attroff(A_REVERSE | A_BOLD);
    refresh();
    while (true) {
        const int key = getch();
        if (key == 'y' || key == 'Y') {
            return 'y';
        }
        if (key == 'n' || key == 'N') {
            return 'n';
        }
        if (key == 'c' || key == 'C' || key == 27) {
            return 'c';
        }
    }
}

void cycleValue(Setting& setting, int direction) {
    const auto current = std::find(setting.choices.begin(), setting.choices.end(), setting.value);
    int index = current == setting.choices.end() ? 0 : static_cast<int>(current - setting.choices.begin());
    const int count = static_cast<int>(setting.choices.size());
    index = (index + direction + count) % count;
    setting.value = setting.choices[static_cast<std::size_t>(index)];
}

bool hasChanges(const std::vector<Setting>& settings, const std::vector<Setting>& savedSettings) {
    for (std::size_t index = 0; index < settings.size(); ++index) {
        if (settings[index].value != savedSettings[index].value) {
            return true;
        }
    }
    return false;
}

int runMenu(const std::string& configPath, const std::string& kconfigPath) {
    std::vector<Setting> settings = loadSettings(configPath, kconfigPath);
    auto savedSettings = settings;
    std::size_t selected = 0;
    std::string status;

    initscr();
    cbreak();
    noecho();
    keypad(stdscr, TRUE);
    curs_set(0);
    if (has_colors()) {
        start_color();
        use_default_colors();
        init_pair(1, COLOR_CYAN, -1);
        init_pair(2, COLOR_GREEN, -1);
    }

    int key = 0;
    bool exitMenu = false;
    while (!exitMenu) {
        drawScreen(settings, selected, status);
        key = getch();
        status.clear();
        switch (key) {
            case KEY_UP:
            case 'k':
                selected = (selected + settings.size() - 1) % settings.size();
                break;
            case KEY_DOWN:
            case 'j':
                selected = (selected + 1) % settings.size();
                break;
            case KEY_LEFT:
                if (settings[selected].isBoolean) {
                    settings[selected].value = settings[selected].value == "y" ? "n" : "y";
                } else {
                    cycleValue(settings[selected], -1);
                }
                break;
            case KEY_RIGHT:
                if (settings[selected].isBoolean) {
                    settings[selected].value = settings[selected].value == "y" ? "n" : "y";
                } else {
                    cycleValue(settings[selected], 1);
                }
                break;
            case ' ':
            case KEY_ENTER:
            case '\n':
            case '\r':
                if (!settings[selected].isBoolean) {
                    const int choice = chooseValue(settings[selected]);
                    if (choice >= 0) {
                        settings[selected].value = settings[selected].choices[static_cast<std::size_t>(choice)];
                    }
                } else {
                    settings[selected].value = settings[selected].value == "y" ? "n" : "y";
                }
                break;
            case 's':
            case 'S': {
                std::string error;
                if (saveSettings(configPath, settings, error)) {
                    status = "Configuration saved to " + configPath;
                    savedSettings = settings;
                } else {
                    status = "Save failed: " + error;
                }
                break;
            }
            case 'r':
            case 'R':
                settings = loadKconfigDefaults(kconfigPath);
                status = "Defaults restored. Press S to save.";
                break;
            case '?':
                showHelp();
                break;
            case 'q':
            case 'Q':
                if (hasChanges(settings, savedSettings)) {
                    const int exitChoice = confirmExit();
                    if (exitChoice == 'c') {
                        break;
                    }
                    if (exitChoice == 'y') {
                        std::string error;
                        if (!saveSettings(configPath, settings, error)) {
                            status = "Save failed: " + error;
                            break;
                        }
                    }
                }
                exitMenu = true;
                break;
            case KEY_RESIZE:
                break;
            default:
                break;
        }
    }

    endwin();
    return 0;
}

}  // namespace

int main(int argc, char** argv) {
    if (argc == 4 && std::string(argv[1]) == "--defconfig") {
        const auto settings = loadKconfigDefaults(argv[2]);
        std::string error;
        if (!saveSettings(argv[3], settings, error)) {
            std::fprintf(stderr, "defconfig failed: %s\n", error.c_str());
            return 1;
        }
        return 0;
    }
    if (argc != 3) {
        std::fprintf(stderr, "Usage: %s CONFIG_FILE KCONFIG_FILE\n", argv[0]);
        return 2;
    }

    if (!isatty(STDIN_FILENO) || !isatty(STDOUT_FILENO)) {
        std::fprintf(stderr, "menuconfig requires an interactive terminal.\n");
        return 2;
    }

    return runMenu(argv[1], argv[2]);
}
