#ifndef VERSION_H
#define VERSION_H

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)
#define AUDIOX_VERSION_STR TOSTRING(AUDIOX_VERSION_MAJOR) "." TOSTRING(AUDIOX_VERSION_MINOR) "." TOSTRING(AUDIOX_VERSION_PATCH)

#endif
